/*
 * This file is generated by jOOQ.
 */
package com.example.purchase_practice_salnikova.jooq.tables.records;


import com.example.purchase_practice_salnikova.jooq.tables.Lot;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LotRecord extends TableRecordImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>purchase.lot.lot_name</code>.
     */
    public void setLotName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>purchase.lot.lot_name</code>.
     */
    public String getLotName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>purchase.lot.customer_code</code>.
     */
    public void setCustomerCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>purchase.lot.customer_code</code>.
     */
    public String getCustomerCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>purchase.lot.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>purchase.lot.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>purchase.lot.currency_code</code>.
     */
    public void setCurrencyCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>purchase.lot.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>purchase.lot.nds_rate</code>.
     */
    public void setNdsRate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>purchase.lot.nds_rate</code>.
     */
    public String getNdsRate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>purchase.lot.place_delivery</code>.
     */
    public void setPlaceDelivery(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>purchase.lot.place_delivery</code>.
     */
    public String getPlaceDelivery() {
        return (String) get(5);
    }

    /**
     * Setter for <code>purchase.lot.date_delivery</code>.
     */
    public void setDateDelivery(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>purchase.lot.date_delivery</code>.
     */
    public LocalDateTime getDateDelivery() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>purchase.lot.id</code>.
     */
    public void setId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>purchase.lot.id</code>.
     */
    public Integer getId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LotRecord
     */
    public LotRecord() {
        super(Lot.LOT);
    }

    /**
     * Create a detached, initialised LotRecord
     */
    public LotRecord(String lotName, String customerCode, BigDecimal price, String currencyCode, String ndsRate, String placeDelivery, LocalDateTime dateDelivery, Integer id) {
        super(Lot.LOT);

        setLotName(lotName);
        setCustomerCode(customerCode);
        setPrice(price);
        setCurrencyCode(currencyCode);
        setNdsRate(ndsRate);
        setPlaceDelivery(placeDelivery);
        setDateDelivery(dateDelivery);
        setId(id);
        resetChangedOnNotNull();
    }
}
