/*
 * This file is generated by jOOQ.
 */
package com.example.purchase_practice_salnikova.jooq.tables;


import com.example.purchase_practice_salnikova.jooq.Purchase;
import com.example.purchase_practice_salnikova.jooq.tables.records.LotRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lot extends TableImpl<LotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>purchase.lot</code>
     */
    public static final Lot LOT = new Lot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LotRecord> getRecordType() {
        return LotRecord.class;
    }

    /**
     * The column <code>purchase.lot.lot_name</code>.
     */
    public final TableField<LotRecord, String> LOT_NAME = createField(DSL.name("lot_name"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.customer_code</code>.
     */
    public final TableField<LotRecord, String> CUSTOMER_CODE = createField(DSL.name("customer_code"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.price</code>.
     */
    public final TableField<LotRecord, BigDecimal> PRICE = createField(DSL.name("price"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>purchase.lot.currency_code</code>.
     */
    public final TableField<LotRecord, String> CURRENCY_CODE = createField(DSL.name("currency_code"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.nds_rate</code>.
     */
    public final TableField<LotRecord, String> NDS_RATE = createField(DSL.name("nds_rate"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.place_delivery</code>.
     */
    public final TableField<LotRecord, String> PLACE_DELIVERY = createField(DSL.name("place_delivery"), SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>purchase.lot.date_delivery</code>.
     */
    public final TableField<LotRecord, LocalDateTime> DATE_DELIVERY = createField(DSL.name("date_delivery"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>purchase.lot.id</code>.
     */
    public final TableField<LotRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    private Lot(Name alias, Table<LotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lot(Name alias, Table<LotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>purchase.lot</code> table reference
     */
    public Lot(String alias) {
        this(DSL.name(alias), LOT);
    }

    /**
     * Create an aliased <code>purchase.lot</code> table reference
     */
    public Lot(Name alias) {
        this(alias, LOT);
    }

    /**
     * Create a <code>purchase.lot</code> table reference
     */
    public Lot() {
        this(DSL.name("lot"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Purchase.PURCHASE;
    }

    @Override
    public Identity<LotRecord, Integer> getIdentity() {
        return (Identity<LotRecord, Integer>) super.getIdentity();
    }

    @Override
    public Lot as(String alias) {
        return new Lot(DSL.name(alias), this);
    }

    @Override
    public Lot as(Name alias) {
        return new Lot(alias, this);
    }

    @Override
    public Lot as(Table<?> alias) {
        return new Lot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(String name) {
        return new Lot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Name name) {
        return new Lot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lot rename(Table<?> name) {
        return new Lot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Condition condition) {
        return new Lot(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lot whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
